const translations = {
  ru: {
    'brand.name': 'BoomBoom Taxi',
    'brand.tagline': 'Водитель сам ставит цену',
    'nav.home': 'Главная',
    'nav.drivers': 'Водителям',
    'nav.passengers': 'Пассажирам',
    'nav.rules': 'Правила сервиса',
    'nav.contacts': 'Контакты',
    'meta.title.home': 'BoomBoom Taxi — водитель сам ставит цену',
    'meta.desc.home': 'BoomBoom Taxi — сервис, где водитель сам ставит цену, а пассажир выбирает прозрачные поездки.',
    'meta.title.drivers': 'BoomBoom Taxi — Информация для водителей',
    'meta.desc.drivers': 'Как водителям работать с BoomBoom Taxi: своя цена, рейтинг, комиссия и безопасность.',
    'meta.title.passengers': 'BoomBoom Taxi — Информация для пассажиров',
    'meta.desc.passengers': 'Как пользоваться BoomBoom Taxi пассажирам: выбор предложений, прозрачные цены и безопасность.',
    'meta.title.rules': 'BoomBoom Taxi — Правила сервиса и отказ от ответственности',
    'meta.desc.rules': 'Правила сервиса BoomBoom Taxi: обязанности водителей и пассажиров, платежи, рейтинг и конфиденциальность.',
    'home.pill': 'Прозрачный сервис без скрытых алгоритмов',
    'home.title': 'BoomBoom Taxi: водитель сам ставит цену',
    'home.subtitle': 'Минимум шума, максимум контроля. Вы выбираете тариф, а пассажир видит итоговую стоимость заранее.',
    'home.cta.driver': 'Стать водителем',
    'home.cta.passenger': 'Выбрать поездку',
    'home.note': 'Честная цена, чёткие правила, защита для водителя и пассажира.',
    'home.card.title': 'Быстрый старт',
    'home.card.item1': 'Тариф по умолчанию: 0.50 € / км и 0.10 € / мин',
    'home.card.item2': 'Можно менять стоимость в любой момент',
    'home.card.item3': 'Оплата: карты, наличные, криптовалюта',
    'home.card.stat1.value': '30 сек',
    'home.card.stat1.label': 'на ответ по заказу',
    'home.card.stat2.value': '4.9 ★',
    'home.card.stat2.label': 'рейтинг влияет на комиссию',
    'home.card.stat3.value': '24/7',
    'home.card.stat3.label': 'поддержка водителей',
    'principles.title': 'Три принципа сервиса',
    'principles.stability.title': 'Стабильность',
    'principles.stability.text': 'Стоимость прозрачна и предсказуема. Вы контролируете цену — пассажир сразу видит итоговую сумму.',
    'principles.speed.title': 'Скорость',
    'principles.speed.text': 'Заказы приходят быстро, без лишнего шума. Решение принять — за вами.',
    'principles.safety.title': 'Гарантия',
    'principles.safety.text': 'Чёткие правила: защита водителя и автомобиля, дисциплина пассажиров, честная история поездок.',
    'drivercard.title': 'Карточка водителя',
    'drivercard.subtitle': 'Пассажиры видят рейтинг, стаж, автомобиль и ваш текущий тариф. Всё просто и без лишних отвлекающих блоков.',
    'drivercard.card.title': 'Что видит пассажир',
    'drivercard.card.item1': 'Тариф: 0.50 € / км · 0.10 € / мин',
    'drivercard.card.item2': 'Стаж: 6 лет, 8 200 поездок',
    'drivercard.card.item3': 'Рейтинг: 4.94, влияет на комиссию',
    'drivercard.card.item4': 'Оплата: карты, наличные, криптовалюта',
    'differ.title': 'Почему BoomBoom Taxi другой',
    'differ.card1.title': 'Водители сами ставят цену',
    'differ.card1.text': 'Нет скрытых алгоритмов. Тариф — ваш выбор, пассажир получает честное предложение.',
    'differ.card2.title': 'Комиссия ниже при рейтинге',
    'differ.card2.text': 'Высокий рейтинг снижает комиссию. Стабильная работа — больше чистый доход.',
    'differ.card3.title': 'Взаимные блокировки',
    'differ.card3.text': 'Водители и пассажиры могут блокировать друг друга на 1 неделю / 1 месяц / 6 месяцев / 1 год / навсегда.',
    'differ.card4.title': 'Каждая 100-я поездка',
    'differ.card4.text': 'Каждая 100-я поездка бесплатна для пассажира (иногда 98-я или 101-я, чтобы исключить злоупотребления).',
    'apps.title': 'Скоро в приложениях',
    'apps.subtitle': 'Делаем две отдельные версии: для водителей и для пассажиров. Удобный старт, понятные заказы, прозрачные выплаты.',
    'apps.driver.title': 'Приложение для водителей',
    'apps.driver.text': 'Управляйте ценой, принимайте заказы, следите за рейтингом и комиссией. Полная история поездок.',
    'apps.passenger.title': 'Приложение для пассажиров',
    'apps.passenger.text': 'Выбирайте лучшее предложение, фиксируйте маршрут, оплачивайте безналично на старте сервиса.',
    'apps.badge.appstore': 'Скоро в App Store',
    'apps.badge.play': 'Скоро в Google Play',
    'contacts.title': 'Свяжитесь с нами',
    'contacts.email': 'support@boomboom.taxi',
    'contacts.phone.label': 'Телефон',
    'contacts.phone.value': '+372 5555 0000',
    'contacts.office.label': 'Офис',
    'contacts.office.value': 'Tallinn, Estonia',
    'footer.copy': '© BoomBoom Taxi, 2025. Platform in development (MVP).',
    'footer.rules': 'Правила сервиса',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.contact': 'contact@boomboom.taxi',
    'drivers.pill': 'Контроль цены и прозрачные поездки',
    'drivers.title': 'Информация для водителей',
    'drivers.subtitle': 'Вы ставите тариф, принимаете заказы и следите за комиссией. Пассажир заранее знает цену и видит ваш стаж.',
    'drivers.cta.faq': 'Частые вопросы',
    'drivers.cta.safety': 'Безопасность',
    'drivers.card.title': 'Быстрые параметры',
    'drivers.card.item1': 'Тариф по умолчанию: 0.50 € / км и 0.10 € / мин',
    'drivers.card.item2': 'Можно менять цену даже во время работы',
    'drivers.card.item3': 'Комиссия зависит от рейтинга и дисциплины',
    'drivers.how.title': 'Как работает сервис',
    'drivers.how.item1': 'Выставляете свой тариф в приложении.',
    'drivers.how.item2': 'Система отправляет заявки по вашему ценнику.',
    'drivers.how.item3': 'На принятие заказа — 30 секунд.',
    'drivers.how.item4': 'После подтверждения — выполняете поездку.',
    'drivers.price.title': 'Своя цена',
    'drivers.price.text': 'Меняйте цену в любое время. В стоимости учтены километры и минуты, отдельно прописываются платные дороги и ожидание.',
    'drivers.price.item1': 'Базовый тариф: 0.50 € / км, 0.10 € / мин.',
    'drivers.price.item2': 'Свободное изменение тарифа по ситуации.',
    'drivers.price.item3': 'Пассажир видит цену до подтверждения.',
    'drivers.rating.title': 'Комиссия и рейтинг',
    'drivers.rating.item1': 'Чем выше рейтинг — тем ниже комиссия.',
    'drivers.rating.item2': 'Пропуск 3 подряд заказов снижает рейтинг на 0.1.',
    'drivers.rating.item3': 'История поездок и начислений всегда доступна.',
    'drivers.docs.title': 'Документы',
    'drivers.docs.item1': 'Водительское удостоверение, страховка, техпаспорт.',
    'drivers.docs.item2': 'Фотография автомобиля и номера.',
    'drivers.docs.item3': 'Подтверждение банковского счёта для выплат.',
    'drivers.safety.title': 'Безопасность',
    'drivers.safety.item1': 'Возможность блокировать пассажира: 1 неделя / 1 месяц / 6 месяцев / 1 год / навсегда.',
    'drivers.safety.item2': 'Пассажиры обязаны соблюдать правила поведения.',
    'drivers.safety.item3': 'Поддержка реагирует 24/7 на обращения водителей.',
    'drivers.faq.title': 'FAQ',
    'drivers.faq.item1': 'Можно ли менять маршрут? Да, система пересчитает стоимость.',
    'drivers.faq.item2': 'Как принимается оплата? На старте — безналично; далее добавим наличные и крипто.',
    'drivers.faq.item3': 'Что если пассажир не выходит? Правила отмены и ожидания указаны в приложении.',
    'passengers.pill': 'Прозрачные цены и выбор водителя',
    'passengers.title': 'Информация для пассажиров',
    'passengers.subtitle': 'Запрашивайте поездку, сравнивайте предложения водителей и выбирайте лучшее. Оплата на старте — безналично.',
    'passengers.cta.request': 'Как заказать поездку',
    'passengers.cta.faq': 'FAQ',
    'passengers.card.title': 'Что важно',
    'passengers.card.item1': 'Пассажир видит цену сразу, без сюрпризов.',
    'passengers.card.item2': 'Выбор водителя по рейтингу, цене и авто.',
    'passengers.card.item3': 'Можно сменить маршрут — система обновит стоимость.',
    'passengers.request.title': 'Как запросить поездку',
    'passengers.request.item1': 'Укажите маршрут и время подачи.',
    'passengers.request.item2': 'Получите предложения водителей с ценой и ETA.',
    'passengers.request.item3': 'Выберите лучшее предложение и подтвердите.',
    'passengers.choose.title': 'Как выбрать водителя',
    'passengers.choose.item1': 'Смотрите рейтинг, авто и стаж.',
    'passengers.choose.item2': 'Выбирайте по цене: драйвер сам ставит тариф.',
    'passengers.choose.item3': 'Каждая 100-я поездка — бесплатна (иногда 98-я или 101-я).',
    'passengers.payment.title': 'Оплата',
    'passengers.payment.text': 'На старте сервиса оплата — только безналично. Далее добавим наличные и криптовалюту.',
    'passengers.payment.item1': 'Карты и Apple/Google Pay.',
    'passengers.payment.item2': 'Чек и история платежей доступны в приложении.',
    'passengers.payment.item3': 'Изменение маршрута пересчитывает стоимость.',
    'passengers.safety.title': 'Безопасность',
    'passengers.safety.item1': 'Можно заблокировать водителя: 1 неделя / 1 месяц / 6 месяцев / 1 год / навсегда.',
    'passengers.safety.item2': 'Водитель видит ваш рейтинг и историю поездок.',
    'passengers.safety.item3': 'Поддержка реагирует 24/7 на обращения.',
    'passengers.faq.title': 'FAQ',
    'passengers.faq.item1': 'Как отменить? Отмена по правилам отображается перед подтверждением.',
    'passengers.faq.item2': 'Что если водитель опаздывает? Можно заменить водителя и выбрать новое предложение.',
    'passengers.faq.item3': 'Есть ли налоги в цене? Да, все сборы включены в итоговую стоимость.',
    'passengers.cta.apps.title': 'Приложение',
    'passengers.cta.apps.text': 'Скоро в App Store и Google Play. Добавим удобное сравнение предложений, историю поездок и быстрые чаевые.',
    'rules.pill': 'Service Rules & Disclaimer',
    'rules.title': 'Правила сервиса BoomBoom Taxi',
    'rules.subtitle': 'Условия использования платформы для водителей и пассажиров, правила оплаты, рейтинга и конфиденциальности.',
    'rules.general.title': 'Общие положения',
    'rules.general.item1': 'BoomBoom Taxi — платформа для поиска поездок; не является перевозчиком.',
    'rules.general.item2': 'Использование сервиса означает согласие с правилами и политикой конфиденциальности.',
    'rules.general.item3': 'Платформа может обновлять правила, уведомляя пользователей.',
    'rules.drivers.title': 'Обязанности водителей',
    'rules.drivers.item1': 'Предоставлять достоверные документы и поддерживать авто в исправном состоянии.',
    'rules.drivers.item2': 'Следовать согласованному маршруту и информировать о его изменении.',
    'rules.drivers.item3': 'Соблюдать правила безопасности и уважительно относиться к пассажирам.',
    'rules.passengers.title': 'Обязанности пассажиров',
    'rules.passengers.item1': 'Указывать правдивый маршрут и быть готовым к посадке вовремя.',
    'rules.passengers.item2': 'Соблюдать правила поведения, не мешать водителю управлять автомобилем.',
    'rules.passengers.item3': 'Следовать инструкциям по оплате и уважать имущество водителя.',
    'rules.platform.title': 'Ответственность платформы',
    'rules.platform.item1': 'Платформа обеспечивает инфраструктуру и поддержку, но не отвечает за действия пользователей.',
    'rules.platform.item2': 'BoomBoom Taxi может приостанавливать доступ при нарушениях правил.',
    'rules.platform.item3': 'В спорных ситуациях платформа помогает собрать информацию для сторон.',
    'rules.payment.title': 'Правила оплаты',
    'rules.payment.item1': 'На старте сервиса — только безналичная оплата.',
    'rules.payment.item2': 'Изменение маршрута пересчитывает итоговую сумму.',
    'rules.payment.item3': 'Комиссия списывается автоматически; водитель получает оговорённую сумму.',
    'rules.rating.title': 'Рейтинг и блокировки',
    'rules.rating.item1': 'Рейтинг влияет на комиссию для водителей и приоритет заказов.',
    'rules.rating.item2': 'Возможны взаимные блокировки: 1 неделя / 1 месяц / 6 месяцев / 1 год / навсегда.',
    'rules.rating.item3': 'Пропуск 3 подряд заказов снижает рейтинг на 0.1.',
    'rules.privacy.title': 'Данные и конфиденциальность',
    'rules.privacy.item1': 'Личные данные используются для обеспечения работы сервиса и безопасности.',
    'rules.privacy.item2': 'Данные могут передаваться партнёрам только по закону и с целью оказания услуг.',
    'rules.privacy.item3': 'Пользователь может запросить удаление или исправление своих данных.'
  },
  en: {
    'brand.name': 'BoomBoom Taxi',
    'brand.tagline': 'Drivers set the price',
    'nav.home': 'Home',
    'nav.drivers': 'Drivers',
    'nav.passengers': 'Passengers',
    'nav.rules': 'Service Rules',
    'nav.contacts': 'Contacts',
    'meta.title.home': 'BoomBoom Taxi — drivers set their own price',
    'meta.desc.home': 'BoomBoom Taxi lets drivers set their own fare while passengers pick transparent rides.',
    'meta.title.drivers': 'BoomBoom Taxi — Driver information',
    'meta.desc.drivers': 'How drivers work with BoomBoom Taxi: own price, rating, commission, and safety.',
    'meta.title.passengers': 'BoomBoom Taxi — Passenger information',
    'meta.desc.passengers': 'How passengers use BoomBoom Taxi: choosing offers, transparent pricing, and safety.',
    'meta.title.rules': 'BoomBoom Taxi — Service Rules & Disclaimer',
    'meta.desc.rules': 'BoomBoom Taxi terms: driver and passenger duties, payments, rating, and privacy.',
    'home.pill': 'Transparent service with no hidden algorithms',
    'home.title': 'BoomBoom Taxi: drivers set the price',
    'home.subtitle': 'Minimal noise, maximum control. You choose the fare; passengers see the final cost upfront.',
    'home.cta.driver': 'Become a driver',
    'home.cta.passenger': 'Pick a ride',
    'home.note': 'Fair pricing, clear rules, and protection for both drivers and passengers.',
    'home.card.title': 'Fast start',
    'home.card.item1': 'Default fare: €0.50 / km and €0.10 / min',
    'home.card.item2': 'You can change the fare anytime',
    'home.card.item3': 'Payments: cards, cash, cryptocurrency',
    'home.card.stat1.value': '30s',
    'home.card.stat1.label': 'to answer a request',
    'home.card.stat2.value': '4.9 ★',
    'home.card.stat2.label': 'rating impacts commission',
    'home.card.stat3.value': '24/7',
    'home.card.stat3.label': 'driver support',
    'principles.title': 'Three service principles',
    'principles.stability.title': 'Stability',
    'principles.stability.text': 'Transparent and predictable pricing. You control the fare; passengers see the total immediately.',
    'principles.speed.title': 'Speed',
    'principles.speed.text': 'Requests arrive fast without noise. Accepting is always your choice.',
    'principles.safety.title': 'Assurance',
    'principles.safety.text': 'Clear rules: driver and vehicle protection, passenger discipline, transparent trip history.',
    'drivercard.title': 'Driver card',
    'drivercard.subtitle': 'Passengers see your rating, experience, vehicle, and current fare. Clean layout, no distractions.',
    'drivercard.card.title': 'Passenger view',
    'drivercard.card.item1': 'Fare: €0.50 / km · €0.10 / min',
    'drivercard.card.item2': 'Experience: 6 years, 8 200 trips',
    'drivercard.card.item3': 'Rating: 4.94, affects commission',
    'drivercard.card.item4': 'Payment: cards, cash, crypto',
    'differ.title': 'Why BoomBoom Taxi is different',
    'differ.card1.title': 'Drivers set their price',
    'differ.card1.text': 'No hidden algorithms. Your fare, your choice; passengers get a fair offer.',
    'differ.card2.title': 'Lower commission with rating',
    'differ.card2.text': 'Higher ratings reduce commission. Consistent work means higher take-home pay.',
    'differ.card3.title': 'Mutual blocking',
    'differ.card3.text': 'Drivers and passengers can block each other for 1 week / 1 month / 6 months / 1 year / forever.',
    'differ.card4.title': 'Every 100th ride',
    'differ.card4.text': 'Every 100th ride is free for the passenger (sometimes 98th or 101st to prevent abuse).',
    'apps.title': 'Coming to apps soon',
    'apps.subtitle': 'Two dedicated versions: for drivers and for passengers. Easy onboarding, clear requests, transparent payouts.',
    'apps.driver.title': 'Driver app',
    'apps.driver.text': 'Control your fare, accept requests, track rating and commission. Full trip history.',
    'apps.passenger.title': 'Passenger app',
    'apps.passenger.text': 'Choose the best offer, lock the route, pay cashless at launch stage.',
    'apps.badge.appstore': 'Coming soon on App Store',
    'apps.badge.play': 'Coming soon on Google Play',
    'contacts.title': 'Contact us',
    'contacts.email': 'support@boomboom.taxi',
    'contacts.phone.label': 'Phone',
    'contacts.phone.value': '+372 5555 0000',
    'contacts.office.label': 'Office',
    'contacts.office.value': 'Tallinn, Estonia',
    'footer.copy': '© BoomBoom Taxi, 2025. Platform in development (MVP).',
    'footer.rules': 'Service Rules',
    'footer.privacy': 'Privacy Policy',
    'footer.contact': 'contact@boomboom.taxi',
    'drivers.pill': 'Price control and transparent trips',
    'drivers.title': 'Driver information',
    'drivers.subtitle': 'Set your fare, accept requests, and track commission. Passengers know the price and see your experience.',
    'drivers.cta.faq': 'FAQ',
    'drivers.cta.safety': 'Safety',
    'drivers.card.title': 'Quick parameters',
    'drivers.card.item1': 'Default fare: €0.50 / km and €0.10 / min',
    'drivers.card.item2': 'Change price even while working',
    'drivers.card.item3': 'Commission depends on rating and discipline',
    'drivers.how.title': 'How it works',
    'drivers.how.item1': 'Set your fare in the app.',
    'drivers.how.item2': 'Requests come with your pricing.',
    'drivers.how.item3': 'You have 30 seconds to accept.',
    'drivers.how.item4': 'After confirmation, complete the ride.',
    'drivers.price.title': 'Your price',
    'drivers.price.text': 'Change pricing anytime. Distance and time are included; tolls and waiting are listed separately.',
    'drivers.price.item1': 'Base fare: €0.50 / km, €0.10 / min.',
    'drivers.price.item2': 'Adjust fares freely to fit the situation.',
    'drivers.price.item3': 'Passengers see cost before confirming.',
    'drivers.rating.title': 'Commission & rating',
    'drivers.rating.item1': 'Higher rating = lower commission.',
    'drivers.rating.item2': 'Skipping 3 requests in a row lowers rating by 0.1.',
    'drivers.rating.item3': 'Trip and payout history always available.',
    'drivers.docs.title': 'Documents',
    'drivers.docs.item1': 'Driving license, insurance, vehicle registration.',
    'drivers.docs.item2': 'Photo of the car and plate.',
    'drivers.docs.item3': 'Bank account confirmation for payouts.',
    'drivers.safety.title': 'Safety',
    'drivers.safety.item1': 'Block passengers for 1 week / 1 month / 6 months / 1 year / forever.',
    'drivers.safety.item2': 'Passengers must follow behavior rules.',
    'drivers.safety.item3': 'Support responds 24/7 to driver issues.',
    'drivers.faq.title': 'FAQ',
    'drivers.faq.item1': 'Can the route change? Yes, the system recalculates price.',
    'drivers.faq.item2': 'How to get paid? At launch cashless only; cash and crypto will be added.',
    'drivers.faq.item3': 'Passenger no-show? Cancellation and waiting rules are in the app.',
    'passengers.pill': 'Transparent fares and driver choice',
    'passengers.title': 'Passenger information',
    'passengers.subtitle': 'Request a ride, compare driver offers, and choose the best. Early stage payments are cashless.',
    'passengers.cta.request': 'How to request a ride',
    'passengers.cta.faq': 'FAQ',
    'passengers.card.title': 'What matters',
    'passengers.card.item1': 'Passengers see price upfront—no surprises.',
    'passengers.card.item2': 'Pick a driver by rating, price, and car.',
    'passengers.card.item3': 'Route changes? The system updates cost.',
    'passengers.request.title': 'How to request a ride',
    'passengers.request.item1': 'Add route and pickup time.',
    'passengers.request.item2': 'Get driver offers with price and ETA.',
    'passengers.request.item3': 'Pick the best offer and confirm.',
    'passengers.choose.title': 'How to choose a driver',
    'passengers.choose.item1': 'Check rating, car, and experience.',
    'passengers.choose.item2': 'Choose by price: driver sets the fare.',
    'passengers.choose.item3': 'Every 100th ride is free (sometimes 98th or 101st).',
    'passengers.payment.title': 'Payment',
    'passengers.payment.text': 'At launch we only support cashless payments. Cash and crypto will follow.',
    'passengers.payment.item1': 'Cards and Apple/Google Pay.',
    'passengers.payment.item2': 'Receipts and history inside the app.',
    'passengers.payment.item3': 'Route changes recalculate the cost.',
    'passengers.safety.title': 'Safety',
    'passengers.safety.item1': 'You can block drivers for 1 week / 1 month / 6 months / 1 year / forever.',
    'passengers.safety.item2': 'Drivers see your rating and trip history.',
    'passengers.safety.item3': 'Support responds 24/7.',
    'passengers.faq.title': 'FAQ',
    'passengers.faq.item1': 'How to cancel? Cancellation policy is shown before confirmation.',
    'passengers.faq.item2': 'Driver late? Switch to another offer.',
    'passengers.faq.item3': 'Are taxes included? Yes, all fees are included in the total.',
    'passengers.cta.apps.title': 'App',
    'passengers.cta.apps.text': 'Coming soon to App Store and Google Play with offer comparison, trip history, and quick tips.',
    'rules.pill': 'Service Rules & Disclaimer',
    'rules.title': 'BoomBoom Taxi Service Rules',
    'rules.subtitle': 'Terms for drivers and passengers, payment rules, rating, and privacy.',
    'rules.general.title': 'General terms',
    'rules.general.item1': 'BoomBoom Taxi is a ride-matching platform; it is not a carrier.',
    'rules.general.item2': 'Using the service means you agree to rules and privacy policy.',
    'rules.general.item3': 'The platform may update rules with notice to users.',
    'rules.drivers.title': 'Driver responsibilities',
    'rules.drivers.item1': 'Provide valid documents and keep the car safe.',
    'rules.drivers.item2': 'Follow the agreed route and inform about changes.',
    'rules.drivers.item3': 'Respect passengers and follow safety rules.',
    'rules.passengers.title': 'Passenger responsibilities',
    'rules.passengers.item1': 'Provide accurate route and be on time for pickup.',
    'rules.passengers.item2': 'Follow behavior rules and do not distract the driver.',
    'rules.passengers.item3': 'Follow payment instructions and respect the vehicle.',
    'rules.platform.title': 'Platform responsibilities',
    'rules.platform.item1': 'The platform provides infrastructure and support but is not liable for user actions.',
    'rules.platform.item2': 'BoomBoom Taxi can suspend access for rule violations.',
    'rules.platform.item3': 'In disputes the platform helps collect information.',
    'rules.payment.title': 'Payment rules',
    'rules.payment.item1': 'At launch only cashless payments are allowed.',
    'rules.payment.item2': 'Route changes recalculate the total.',
    'rules.payment.item3': 'Commission is charged automatically; drivers receive the agreed amount.',
    'rules.rating.title': 'Rating system & blocking',
    'rules.rating.item1': 'Rating affects driver commission and request priority.',
    'rules.rating.item2': 'Mutual blocks: 1 week / 1 month / 6 months / 1 year / forever.',
    'rules.rating.item3': 'Skipping 3 requests in a row decreases rating by 0.1.',
    'rules.privacy.title': 'Data and privacy',
    'rules.privacy.item1': 'Personal data is used to operate the service and keep users safe.',
    'rules.privacy.item2': 'Data may be shared with partners only legally and to deliver services.',
    'rules.privacy.item3': 'Users can request deletion or correction of their data.'
  },
  lv: {
    'brand.name': 'BoomBoom Taxi',
    'brand.tagline': 'Vadītājs nosaka cenu',
    'nav.home': 'Sākums',
    'nav.drivers': 'Vadītājiem',
    'nav.passengers': 'Pasažieriem',
    'nav.rules': 'Pakalpojuma noteikumi',
    'nav.contacts': 'Kontakti',
    'meta.title.home': 'BoomBoom Taxi — vadītājs pats nosaka cenu',
    'meta.desc.home': 'BoomBoom Taxi ļauj vadītājiem pašiem noteikt tarifu, pasažieri redz caurspīdīgas brauciena izmaksas.',
    'meta.title.drivers': 'BoomBoom Taxi — Informācija vadītājiem',
    'meta.desc.drivers': 'Kā strādāt ar BoomBoom Taxi: sava cena, reitings, komisija un drošība.',
    'meta.title.passengers': 'BoomBoom Taxi — Informācija pasažieriem',
    'meta.desc.passengers': 'Kā izmantot BoomBoom Taxi pasažieriem: piedāvājumu izvēle, caurspīdīgas cenas un drošība.',
    'meta.title.rules': 'BoomBoom Taxi — Pakalpojuma noteikumi',
    'meta.desc.rules': 'Noteikumi vadītājiem un pasažieriem, maksājumi, reitingi un privātums.',
    'home.pill': 'Caurspīdīgs serviss bez slēptiem algoritmiem',
    'home.title': 'BoomBoom Taxi: vadītājs nosaka cenu',
    'home.subtitle': 'Maz trokšņa, maksimāla kontrole. Jūs izvēlaties tarifu; pasažieris redz gala cenu uzreiz.',
    'home.cta.driver': 'Kļūt par vadītāju',
    'home.cta.passenger': 'Izvēlēties braucienu',
    'home.note': 'Godīgas cenas, skaidri noteikumi un aizsardzība vadītājiem un pasažieriem.',
    'home.card.title': 'Ātrs starts',
    'home.card.item1': 'Noklusējuma tarifs: 0.50 € / km un 0.10 € / min',
    'home.card.item2': 'Tarifu var mainīt jebkurā brīdī',
    'home.card.item3': 'Maksājumi: kartes, skaidra nauda, kriptovalūta',
    'home.card.stat1.value': '30 s',
    'home.card.stat1.label': 'atbildei uz pieprasījumu',
    'home.card.stat2.value': '4.9 ★',
    'home.card.stat2.label': 'reitings ietekmē komisiju',
    'home.card.stat3.value': '24/7',
    'home.card.stat3.label': 'vadītāju atbalsts',
    'principles.title': 'Trīs servisa principi',
    'principles.stability.title': 'Stabilitāte',
    'principles.stability.text': 'Caurspīdīgas un prognozējamas izmaksas. Jūs kontrolējat cenu — pasažieris uzreiz redz summu.',
    'principles.speed.title': 'Ātrums',
    'principles.speed.text': 'Pieprasījumi pienāk ātri un bez traucēkļiem. Pieņemt vai noraidīt — jūsu izvēle.',
    'principles.safety.title': 'Drošība',
    'principles.safety.text': 'Skaidri noteikumi: vadītāja un auto aizsardzība, pasažieru disciplīna, caurspīdīga vēsture.',
    'drivercard.title': 'Vadītāja karte',
    'drivercard.subtitle': 'Pasažieri redz jūsu reitingu, stāžu, auto un pašreizējo tarifu. Vienkārši un bez liekām detaļām.',
    'drivercard.card.title': 'Ko redz pasažieris',
    'drivercard.card.item1': 'Tarifs: 0.50 € / km · 0.10 € / min',
    'drivercard.card.item2': 'Stāžs: 6 gadi, 8 200 braucieni',
    'drivercard.card.item3': 'Reitings: 4.94, ietekmē komisiju',
    'drivercard.card.item4': 'Apmaksa: kartes, skaidra nauda, kripto',
    'differ.title': 'Kāpēc BoomBoom Taxi ir citāds',
    'differ.card1.title': 'Vadītāji nosaka cenu',
    'differ.card1.text': 'Nav slēptu algoritmu. Tarifs ir jūsu izvēle, pasažieris saņem godīgu piedāvājumu.',
    'differ.card2.title': 'Mazāka komisija ar labu reitingu',
    'differ.card2.text': 'Augstāks reitings samazina komisiju. Stabils darbs — lielāki ienākumi.',
    'differ.card3.title': 'Savstarpēja bloķēšana',
    'differ.card3.text': 'Vadītāji un pasažieri var bloķēt viens otru uz 1 nedēļu / 1 mēnesi / 6 mēnešiem / 1 gadu / uz visiem laikiem.',
    'differ.card4.title': 'Katrs 100. brauciens',
    'differ.card4.text': 'Katrs 100. brauciens pasažierim ir bez maksas (dažreiz 98. vai 101., lai novērstu ļaunprātību).',
    'apps.title': 'Drīzumā lietotnēs',
    'apps.subtitle': 'Divas versijas: vadītājiem un pasažieriem. Ērta uzsākšana, skaidri pieprasījumi, caurspīdīgi maksājumi.',
    'apps.driver.title': 'Lietotne vadītājiem',
    'apps.driver.text': 'Kontrolējiet cenu, pieņemiet pieprasījumus, sekojiet reitingam un komisijai. Pilna braucienu vēsture.',
    'apps.passenger.title': 'Lietotne pasažieriem',
    'apps.passenger.text': 'Izvēlieties labāko piedāvājumu, fiksējiet maršrutu, sākumā apmaksājiet bezskaidrā.',
    'apps.badge.appstore': 'Drīzumā App Store',
    'apps.badge.play': 'Drīzumā Google Play',
    'contacts.title': 'Sazinieties ar mums',
    'contacts.email': 'support@boomboom.taxi',
    'contacts.phone.label': 'Tālrunis',
    'contacts.phone.value': '+372 5555 0000',
    'contacts.office.label': 'Birojs',
    'contacts.office.value': 'Tallina, Igaunija',
    'footer.copy': '© BoomBoom Taxi, 2025. Platforma izstrādē (MVP).',
    'footer.rules': 'Pakalpojuma noteikumi',
    'footer.privacy': 'Privātuma politika',
    'footer.contact': 'contact@boomboom.taxi',
    'drivers.pill': 'Cenas kontrole un caurspīdīgi braucieni',
    'drivers.title': 'Informācija vadītājiem',
    'drivers.subtitle': 'Jūs nosakāt tarifu, pieņemat pieprasījumus un redzat komisiju. Pasažieris iepriekš zina cenu un jūsu stāžu.',
    'drivers.cta.faq': 'Biežākie jautājumi',
    'drivers.cta.safety': 'Drošība',
    'drivers.card.title': 'Ātrie parametri',
    'drivers.card.item1': 'Noklusējuma tarifs: 0.50 € / km un 0.10 € / min',
    'drivers.card.item2': 'Var mainīt cenu arī darba laikā',
    'drivers.card.item3': 'Komisija atkarīga no reitinga un disciplīnas',
    'drivers.how.title': 'Kā darbojas',
    'drivers.how.item1': 'Iestatiet tarifu lietotnē.',
    'drivers.how.item2': 'Pieprasījumi nāk pēc jūsu cenām.',
    'drivers.how.item3': 'Ir 30 sekundes, lai pieņemtu.',
    'drivers.how.item4': 'Pēc apstiprinājuma veicat braucienu.',
    'drivers.price.title': 'Jūsu cena',
    'drivers.price.text': 'Mainiet cenu jebkurā laikā. Attālums un laiks iekļauts; maksas ceļi un gaidīšana norādīti atsevišķi.',
    'drivers.price.item1': 'Bāzes tarifs: 0.50 € / km, 0.10 € / min.',
    'drivers.price.item2': 'Brīvi pielāgojiet tarifus situācijai.',
    'drivers.price.item3': 'Pasažieris redz cenu pirms apstiprināšanas.',
    'drivers.rating.title': 'Komisija un reitings',
    'drivers.rating.item1': 'Augstāks reitings = zemāka komisija.',
    'drivers.rating.item2': 'Izlaižot 3 pieprasījumus pēc kārtas, reitings samazinās par 0.1.',
    'drivers.rating.item3': 'Braucienu un maksājumu vēsture vienmēr pieejama.',
    'drivers.docs.title': 'Dokumenti',
    'drivers.docs.item1': 'Vadītāja apliecība, apdrošināšana, tehniskā pase.',
    'drivers.docs.item2': 'Auto un numura foto.',
    'drivers.docs.item3': 'Bankas konta apstiprinājums izmaksām.',
    'drivers.safety.title': 'Drošība',
    'drivers.safety.item1': 'Var bloķēt pasažieri uz 1 nedēļu / 1 mēnesi / 6 mēnešiem / 1 gadu / uz visiem laikiem.',
    'drivers.safety.item2': 'Pasažieri ievēro uzvedības noteikumus.',
    'drivers.safety.item3': 'Atbalsts reaģē 24/7 uz vadītāju jautājumiem.',
    'drivers.faq.title': 'FAQ',
    'drivers.faq.item1': 'Vai var mainīt maršrutu? Jā, sistēma pārrēķinās cenu.',
    'drivers.faq.item2': 'Kā saņemt maksājumu? Sākumā tikai bezskaidras; vēlāk pievienosim skaidru naudu un kripto.',
    'drivers.faq.item3': 'Pasažieris neierodas? Atcelšanas un gaidīšanas noteikumi ir lietotnē.',
    'passengers.pill': 'Caurspīdīgas cenas un vadītāja izvēle',
    'passengers.title': 'Informācija pasažieriem',
    'passengers.subtitle': 'Pieprasiet braucienu, salīdziniet piedāvājumus un izvēlieties labāko. Sākumā apmaksa tikai bezskaidras.',
    'passengers.cta.request': 'Kā pasūtīt braucienu',
    'passengers.cta.faq': 'FAQ',
    'passengers.card.title': 'Svarīgais',
    'passengers.card.item1': 'Cena redzama uzreiz, bez pārsteigumiem.',
    'passengers.card.item2': 'Vadītāja izvēle pēc reitinga, cenas un auto.',
    'passengers.card.item3': 'Maršruta maiņa? Sistēma atjaunina cenu.',
    'passengers.request.title': 'Kā pieprasīt braucienu',
    'passengers.request.item1': 'Norādiet maršrutu un izsaukuma laiku.',
    'passengers.request.item2': 'Saņemiet vadītāju piedāvājumus ar cenu un ETA.',
    'passengers.request.item3': 'Izvēlieties labāko piedāvājumu un apstipriniet.',
    'passengers.choose.title': 'Kā izvēlēties vadītāju',
    'passengers.choose.item1': 'Pārbaudiet reitingu, auto un stāžu.',
    'passengers.choose.item2': 'Izvēlieties pēc cenas: vadītājs nosaka tarifu.',
    'passengers.choose.item3': 'Katrs 100. brauciens bez maksas (dažreiz 98. vai 101.).',
    'passengers.payment.title': 'Apmaksa',
    'passengers.payment.text': 'Sākumā pieņemam tikai bezskaidras naudas maksājumus. Vēlāk pievienosim skaidru naudu un kripto.',
    'passengers.payment.item1': 'Kartes un Apple/Google Pay.',
    'passengers.payment.item2': 'Čeks un maksājumu vēsture lietotnē.',
    'passengers.payment.item3': 'Maršruta maiņa pārrēķina izmaksas.',
    'passengers.safety.title': 'Drošība',
    'passengers.safety.item1': 'Var bloķēt vadītāju uz 1 nedēļu / 1 mēnesi / 6 mēnešiem / 1 gadu / uz visiem laikiem.',
    'passengers.safety.item2': 'Vadītājs redz jūsu reitingu un braucienu vēsturi.',
    'passengers.safety.item3': 'Atbalsts reaģē 24/7.',
    'passengers.faq.title': 'FAQ',
    'passengers.faq.item1': 'Kā atcelt? Atcelšanas noteikumi redzami pirms apstiprināšanas.',
    'passengers.faq.item2': 'Vadītājs kavējas? Varat izvēlēties citu piedāvājumu.',
    'passengers.faq.item3': 'Vai cena ietver nodokļus? Jā, visi maksājumi ir iekļauti.',
    'passengers.cta.apps.title': 'Lietotne',
    'passengers.cta.apps.text': 'Drīzumā App Store un Google Play ar piedāvājumu salīdzināšanu, braucienu vēsturi un ātriem dzeramnaudas rīkiem.',
    'rules.pill': 'Pakalpojuma noteikumi un atruna',
    'rules.title': 'BoomBoom Taxi pakalpojuma noteikumi',
    'rules.subtitle': 'Nosacījumi vadītājiem un pasažieriem, maksājumi, reitingi un privātums.',
    'rules.general.title': 'Vispārīgie noteikumi',
    'rules.general.item1': 'BoomBoom Taxi ir platforma braucienu meklēšanai; tā nav pārvadātājs.',
    'rules.general.item2': 'Izmantojot servisu, jūs piekrītat noteikumiem un privātuma politikai.',
    'rules.general.item3': 'Platforma var atjaunināt noteikumus, paziņojot lietotājiem.',
    'rules.drivers.title': 'Vadītāju pienākumi',
    'rules.drivers.item1': 'Nodrošināt derīgus dokumentus un uzturēt auto kārtībā.',
    'rules.drivers.item2': 'Sekot saskaņotajam maršrutam un informēt par izmaiņām.',
    'rules.drivers.item3': 'Ievērot drošību un cienīt pasažierus.',
    'rules.passengers.title': 'Pasažieru pienākumi',
    'rules.passengers.item1': 'Norādīt patiesu maršrutu un būt laikā uz iekāpšanu.',
    'rules.passengers.item2': 'Ievērot uzvedības noteikumus un netraucēt vadītāju.',
    'rules.passengers.item3': 'Sekot maksājumu instrukcijām un cienīt auto.',
    'rules.platform.title': 'Platformas atbildība',
    'rules.platform.item1': 'Platforma nodrošina infrastruktūru un atbalstu, bet neatbild par lietotāju rīcību.',
    'rules.platform.item2': 'BoomBoom Taxi var apturēt piekļuvi noteikumu pārkāpumu gadījumā.',
    'rules.platform.item3': 'Strīdos platforma palīdz savākt informāciju.',
    'rules.payment.title': 'Maksājumu noteikumi',
    'rules.payment.item1': 'Sākumā atļauti tikai bezskaidras naudas maksājumi.',
    'rules.payment.item2': 'Maršruta maiņa pārrēķina gala summu.',
    'rules.payment.item3': 'Komisija tiek ieturēta automātiski; vadītājs saņem vienošanos summu.',
    'rules.rating.title': 'Reitingi un bloķēšana',
    'rules.rating.item1': 'Reitings ietekmē komisiju un pieprasījumu prioritāti vadītājiem.',
    'rules.rating.item2': 'Savstarpēja bloķēšana: 1 nedēļa / 1 mēnesis / 6 mēneši / 1 gads / uz visiem laikiem.',
    'rules.rating.item3': 'Izlaižot 3 pieprasījumus pēc kārtas, reitings samazinās par 0.1.',
    'rules.privacy.title': 'Dati un privātums',
    'rules.privacy.item1': 'Personas dati tiek izmantoti servisa darbībai un drošībai.',
    'rules.privacy.item2': 'Dati tiek nodoti partneriem tikai likumīgi un pakalpojuma nodrošināšanai.',
    'rules.privacy.item3': 'Lietotājs var pieprasīt savu datu dzēšanu vai labošanu.'
  }
};

const applyTranslations = (lang) => {
  const dict = translations[lang] || translations.ru;
  document.querySelectorAll('[data-i18n]').forEach((node) => {
    const key = node.getAttribute('data-i18n');
    const value = dict[key];
    if (!value) return;
    if (node.tagName === 'META') {
      node.setAttribute('content', value);
    } else if (node.tagName === 'TITLE') {
      node.textContent = value;
    } else {
      node.textContent = value;
    }
  });
  document.documentElement.setAttribute('lang', lang);
  localStorage.setItem('bbt-lang', lang);
  document.querySelectorAll('.lang-btn').forEach((btn) => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
};

const setupLanguage = () => {
  const saved = localStorage.getItem('bbt-lang');
  const initial = saved || document.documentElement.lang || 'ru';
  applyTranslations(initial);
  document.querySelectorAll('.lang-btn').forEach((btn) => {
    btn.addEventListener('click', () => applyTranslations(btn.dataset.lang));
  });
};

const setupBurger = () => {
  const burger = document.querySelector('.burger');
  const nav = document.querySelector('.site-nav');
  if (!burger || !nav) return;
  burger.addEventListener('click', () => {
    const open = nav.classList.toggle('open');
    burger.setAttribute('aria-expanded', open);
  });
  nav.querySelectorAll('a').forEach((link) => {
    link.addEventListener('click', () => {
      nav.classList.remove('open');
      burger.setAttribute('aria-expanded', 'false');
    });
  });
};

window.addEventListener('DOMContentLoaded', () => {
  setupBurger();
  setupLanguage();
});
